# Experiment Settings
exp_dir: experiments/default
seed: 0
cuda: True
log_level: info
log_every: 10

# Data Settings
train_src: data/train.de-en.de.wmixerprep
train_tgt: data/train.de-en.en.wmixerprep
dev_src: data/valid.de-en.de.wmixerprep
dev_tgt: data/valid.de-en.en.wmixerprep
test_src: data/test.de-en.de.wmixerprep
test_tgt: data/test.de-en.en.wmixerprep
vocab_size: 50000
vocab_freq_cutoff: 2

# Model Settings
encoder_embed_size: 256
encoder_hidden_size: 256
decoder_embed_size: 256
decoder_hidden_size: 256
uniform_init: 0.1
encoder_layers: 2
decoder_layers: 2

# Train Settings
max_epoch: 30
lr: 0.001
clip_grad: 5.0
batch_size: 64
dropout: 0.2

# Decode Settings
model_file: model_mle.pth
output_file: decode.txt
max_decoding_time_step: 100
beam_size: 5
decode_dev_src: data/valid.de-en.de
decode_dev_tgt: data/valid.de-en.en
decode_test_src: data/test.de-en.de
decode_test_tgt: data/test.de-en.en
